{
 "title": "ISA dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Broj trenutno aktivnih korisnika u toku 24h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "active_users_last_24h" }
   ]
  },
  {
   "title": "prosečno trajanje HTTP zahteva za kreiranje nove objave u toku 24h ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{method=\"POST\", uri=\"/api/posts\"}[24h]) / rate(http_server_requests_seconds_count{method=\"POST\", uri=\"/api/posts\"}[24h])"
    }
   ]
  },
  {
   "title": "prosečno zauzeće CPU u određenom vremenskom intervalu ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg_over_time(process_cpu_usage[5m])"
    }
   ]
  }
 ]
}